# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

name: 🆕 Feature
description: The solution to a Problem.
labels: ["triage"]
type: "Feature"
projects: ["GoCheckIt/3"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem(s) will this feature solve?
      description: 'Describe or reference the problem. Link to specific GitHub issues if logged. Type # to get started.'
    validations:
      required: true
  - type: textarea
    id: specification
    attributes:
      label: Feature Description
      description: Describe the feature requirements and limitations.
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Helpful references
      description: Links, pictures or other designs which solve the same problem.